---
# Source: kafka/templates/schema-registry/forecastle.yaml
apiVersion: forecastle.stakater.com/v1alpha1
kind: ForecastleApp
metadata:
  name: kafka-schema-registry
spec:
  name: schema-registry
  group: steadforce-infrastructure
  icon: https://minio.steadops.local.steadforce.com/forecastle/icons/schema-registry.png
  url: https://schema-registry.steadops.local.steadforce.com
