---
# Source: akhq/charts/akhq/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: kafka-akhq-secrets
  labels:
    app.kubernetes.io/name: akhq
    helm.sh/chart: akhq-0.26.0
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  application-secrets.yml: "YWtocToKICBjb25uZWN0aW9uczoKICAgIGthZmthOgogICAgICBwcm9wZXJ0aWVzOgogICAgICAgIGJvb3RzdHJhcC5zZXJ2ZXJzOiBrYWZrYS1rYWZrYS1ib290c3RyYXAua2Fma2Euc3ZjLmNsdXN0ZXIubG9jYWw6OTA5MgogICAgICBzY2hlbWEtcmVnaXN0cnk6CiAgICAgICAgdXJsOiBodHRwOi8va2Fma2Etc2NoZW1hLXJlZ2lzdHJ5OjgwODE="
