apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.schemaRegistry.application.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.schemaRegistry.application.name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.schemaRegistry.application.name }}
    spec:
      containers:
      - name: schema-registry
        image: {{ .Values.schemaRegistry.image.repository }}:{{ .Values.schemaRegistry.image.tag }}
        env:
        - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
          value: {{ .Values.schemaRegistry.bootstrap_servers }}
        - name: SCHEMA_REGISTRY_KAFKASTORE_GROUP_ID
          value: {{ .Values.schemaRegistry.group_id }}
        - name: SCHEMA_REGISTRY_KAFKASTORE_TOPIC
          value: {{ .Values.schemaRegistry.topic }}
        - name: SCHEMA_REGISTRY_LISTENERS
          value: "http://0.0.0.0:8081"
        - name: SCHEMA_REGISTRY_HOST_NAME
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          {{- toYaml .Values.schemaRegistry.resources | nindent 10 }}
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP